default: &default
  adapter: <%= Rails.application.secrets.blacklight_adapter %>
  url: <%= Rails.application.secrets.solr_url %>
development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
