development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/development" %>
test:
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:8983/solr/test" %>
staging:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>
