default: &default
  user: <%= Rails.application.secrets.fedora_user %>
  password: <%= Rails.application.secrets.fedora_password %>
  url: <%= Rails.application.secrets.fedora_url %>
  base_path: <%= Rails.application.secrets.fedora_basepath %>
development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
