default: &default
  url: Rails.application.secrets.redis_url 

# environment variable REDIS_URL can be configured to contain all information needed to connect to redis server
# e.g. redis://:p4ssw0rd@10.0.1.1:6380/15, which include the URL, username/password as required, port number, db etc

development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
